services:
  fynvi-share:
    container_name: fynvi-share
    image: libaxnie/fynvi-share:latest
    restart: unless-stopped
    ports:
      - "3000:3000"
    environment:
      - TRUST_PROXY=false
      - APP_URL=http://localhost:3000
    volumes:
      - "./data:/opt/app/backend/data:rw,z"
      - "./data/images:/opt/app/frontend/public/img:rw,z"
      # - "./config.yaml:/opt/app/config.yaml" # Optional file-based config override
